/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gescom;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author JeffrickTenefeut
 */
public class GesAchats extends javax.swing.JPanel {

    /**
     * Creates new form GesAchats
     */
    public GesAchats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        quantité = new javax.swing.JTextField();
        Annuler = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        Ajouter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        R = new javax.swing.JTextArea();
        prixUnitaire = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateVente = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        Annuler1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setDoubleBuffered(false);
        setInheritsPopupMenu(true);
        setPreferredSize(new java.awt.Dimension(807, 717));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 155, 228));
        jLabel1.setText("Type de Parpaing");
        jLabel1.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 155, 228));
        jLabel2.setText("Quantités");
        jLabel2.setAutoscrolls(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 155, 228));
        jLabel3.setText("Prix Unitaire");
        jLabel3.setAutoscrolls(true);

        combobox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        combobox.setForeground(new java.awt.Color(76, 155, 228));
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parpaing 10", "Parpaing 12", "Parpaing 15", "Parpaing  20", "Hourdis" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 155, 228));
        jLabel4.setText("Prix Total");
        jLabel4.setAutoscrolls(true);

        quantité.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        quantité.setForeground(new java.awt.Color(76, 155, 228));
        quantité.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantité.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantitéFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantitéFocusLost(evt);
            }
        });
        quantité.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitéActionPerformed(evt);
            }
        });
        quantité.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantitéKeyPressed(evt);
            }
        });

        Annuler.setBackground(new java.awt.Color(255, 255, 255));
        Annuler.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Annuler.setForeground(new java.awt.Color(76, 155, 228));
        Annuler.setText("RESSET");
        Annuler.setBorder(null);
        Annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AnnulerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AnnulerMouseExited(evt);
            }
        });
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        total.setForeground(new java.awt.Color(76, 155, 228));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Ajouter.setBackground(new java.awt.Color(255, 255, 255));
        Ajouter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Ajouter.setForeground(new java.awt.Color(76, 155, 228));
        Ajouter.setText("AJOUTER P");
        Ajouter.setBorder(null);
        Ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjouterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AjouterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AjouterMouseExited(evt);
            }
        });
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        R.setBackground(new java.awt.Color(76, 155, 228));
        R.setColumns(20);
        R.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        R.setForeground(new java.awt.Color(255, 255, 255));
        R.setRows(5);
        R.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R.setEnabled(false);
        jScrollPane2.setViewportView(R);

        prixUnitaire.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        prixUnitaire.setForeground(new java.awt.Color(76, 155, 228));
        prixUnitaire.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prixUnitaire.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prixUnitaireFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prixUnitaireFocusLost(evt);
            }
        });
        prixUnitaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixUnitaireActionPerformed(evt);
            }
        });
        prixUnitaire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prixUnitaireKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(78, 155, 228));
        jLabel5.setText("Date de vente");

        dateVente.setDateFormatString("yyyy-MMM-d");
        dateVente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(78, 155, 228));
        jLabel6.setText("Nom du Client");

        nom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nom.setForeground(new java.awt.Color(78, 155, 228));
        nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom.setToolTipText("");

        Annuler1.setBackground(new java.awt.Color(255, 255, 255));
        Annuler1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Annuler1.setForeground(new java.awt.Color(76, 155, 228));
        Annuler1.setText("NOUVELLE C");
        Annuler1.setBorder(null);
        Annuler1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Annuler1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Annuler1MouseExited(evt);
            }
        });
        Annuler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Annuler1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(78, 155, 228));
        jLabel7.setText("Contact");

        contact.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        contact.setForeground(new java.awt.Color(78, 155, 228));
        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contact.setToolTipText("");
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(Annuler1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(prixUnitaire, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                    .addComponent(combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateVente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(122, 122, 122))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantité, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contact))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nom)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(nom, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantité, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prixUnitaire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateVente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Annuler1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerMouseEntered
        // TODO add your handling code here:
         Annuler.setBackground(new Color(76,155,228));
         Annuler.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_AnnulerMouseEntered

    private void AnnulerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerMouseExited
        // TODO add your handling code here:
         Annuler.setForeground(new Color(76,155,228));
         Annuler.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_AnnulerMouseExited

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
        String combo = combobox.getSelectedItem().toString();
       
    }//GEN-LAST:event_comboboxActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        prixUnitaire.setText("");
        quantité.setText("");
        total.setText("");
    }//GEN-LAST:event_AnnulerActionPerformed

    private void quantitéKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantitéKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_quantitéKeyPressed

    private void quantitéFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantitéFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_quantitéFocusLost

    private void quantitéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitéActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_quantitéActionPerformed

    private void AjouterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterMouseEntered
        // TODO add your handling code here:
        Ajouter.setBackground(new Color(76,155,228));
         Ajouter.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_AjouterMouseEntered

    private void AjouterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterMouseExited
        // TODO add your handling code here:
         Ajouter.setForeground(new Color(76,155,228));
         Ajouter.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_AjouterMouseExited

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AjouterActionPerformed

    private void AjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterMouseClicked
        // TODO add your handling code here:
  
        int entier=Integer.parseInt(contact.getText());
         if(prixUnitaire.getText().length()<=2 || quantité.getText().length()<2 || nom.getText().length()<3 || contact.getText().length()<9){
            prixUnitaire.setText("0");
            quantité.setText("0");
            Integer unitaire=Integer.parseInt(prixUnitaire.getText());
            Integer quantite=Integer.parseInt(quantité.getText());
            Integer totale=unitaire * quantite;
            total.setText(totale+"FCFA");
            ajoutErreur ajerreur=new ajoutErreur();
            ajerreur.setVisible(true);
        }else{
            Integer unitaire=Integer.parseInt(prixUnitaire.getText());
            Integer quantite=Integer.parseInt(quantité.getText());
            Integer totale=unitaire * quantite;
            total.setText(totale+"FCFA");
            R.setText(R.getText()+quantité.getText()+" Parpaing de "+combobox.getSelectedItem()+" d'une somme de "+total.getText()+" a été ajouter\n");
            try{
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gescom","root","");
                PreparedStatement requette=con.prepareStatement("INSERT INTO vente (nom_client,contact_client,produit,quantite,prix_unitaire,prix_total,date_vente) VALUES (?,?,?,?,?,?,?)");
                requette.setString(1,nom.getText());
                requette.setString(2, contact.getText());
                requette.setString(3, combobox.getSelectedItem().toString());
                requette.setInt(4, quantite);
                requette.setInt(5, unitaire);
                requette.setInt(6, totale);
                requette.setString(7, dateVente.getDate().toString());
                requette.executeUpdate();
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
      
    }//GEN-LAST:event_AjouterMouseClicked

    private void quantitéFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantitéFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_quantitéFocusGained

    private void prixUnitaireFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prixUnitaireFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_prixUnitaireFocusGained

    private void prixUnitaireFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prixUnitaireFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_prixUnitaireFocusLost

    private void prixUnitaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixUnitaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixUnitaireActionPerformed

    private void prixUnitaireKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixUnitaireKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixUnitaireKeyPressed

    private void Annuler1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Annuler1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Annuler1MouseEntered

    private void Annuler1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Annuler1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Annuler1MouseExited

    private void Annuler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annuler1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Annuler1ActionPerformed

    private void contactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()!=1 && evt.getKeyCode()!=2 && evt.getKeyCode()!=3 && evt.getKeyCode()!=4 && evt.getKeyCode()!=5 && evt.getKeyCode()!=6 && evt.getKeyCode()!=7 && evt.getKeyCode()!=8 && evt.getKeyCode()!=9 && evt.getKeyCode()!=0){
            JOptionPane.showMessageDialog(this, "veuiellez entrer le bon type de donne");
        }
        

    }//GEN-LAST:event_contactKeyPressed

    private void contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_contactKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton Annuler;
    private javax.swing.JButton Annuler1;
    private javax.swing.JTextArea R;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JTextField contact;
    private com.toedter.calendar.JDateChooser dateVente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prixUnitaire;
    private javax.swing.JTextField quantité;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
